# Default Spark cluster settings for this Docker Compose setup
spark.master                        spark://spark-driver:7077
spark.eventLog.enabled              true
spark.eventLog.dir                  file:///opt/spark/spark-events
spark.history.fs.logDirectory       file:///opt/spark/spark-events
spark.ui.showConsoleProgress        true
